/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package wheather.app

import main.kotlin.wheather.app.filter.CityFilter
import main.kotlin.wheather.app.filter.DayFilter
import main.kotlin.wheather.app.weather.Weather
import main.kotlin.wheather.app.weather.WeatherInfo
import java.util.*

enum class Day {
    MON, TUE, WED, THU, FRI, SAT, SUN
}

val weatherList = listOf(
    WeatherInfo(Weather.SUNNY, 30, Day.MON, "Jakarta"),
    WeatherInfo(Weather.CLOUDY, 20, Day.TUE, "Jakarta"),
    WeatherInfo(Weather.SUNNY, 33, Day.WED, "Jakarta"),
    WeatherInfo(Weather.RAINY, 17, Day.THU, "Jakarta"),
    WeatherInfo(Weather.WINDY, 18, Day.FRI, "Jakarta"),
    WeatherInfo(Weather.WINDY, 18, Day.MON, "Bangalore"),
    WeatherInfo(Weather.WINDY, 18, Day.TUE, "Bangalore"),
    WeatherInfo(Weather.WINDY, 18, Day.WED, "Bangalore"),
    WeatherInfo(Weather.WINDY, 18, Day.THU, "Bangalore"),
    WeatherInfo(Weather.WINDY, 18, Day.FRI, "Bangalore")

)

class App {

    private val filter = DayFilter.getInstance()

    fun accept(input: String){

        val result = filter.filter(weatherList, input)
        filter.print(result)
        println("")
    }
}


fun main() {
    val app = App()
    val running = true
    val scanner = Scanner(System.`in`)

    while(running){
        println("Input the name of the city: ")
        val input = scanner.nextLine()
        app.accept(input)
    }
}
